### ISSUE TITLE
Boot loading stuck at IOConsoleUsers

### ISSUE THREAD

**Issue by Andr3y-** [dhckdgjs/GIGABYTE-Z590-VISION-G-HACKINTOSH-OPENCORE-iGPU-with-dGPU-UHD630-RX580#1]
Hey, thanks for posting your guide. 

1. I tried following it and I am getting the following error after which I am stuck:

`IOConsoleUsers: gIOSScreenLockState 3, hs 0, bs0, now 0, sm 0x0`

How do I solve it?

2. Also you mentioned that you changed your Initial Display Output(Gigabyte) to iGPU. 
I don't have this option in BIOS, where do I find it?

Here's my HW list:
|[CPU][Intel Core i9-10850K 3.6 GHz 10-Core Processor]
|[Motherboard][Gigabyte Z590 VISION D ATX LGA1200 Motherboard]
|[Memory][G.Skill Trident Z RGB 32 GB (2 x 16 GB) DDR4-3600 CL17 Memory]
|[Storage][Samsung 970 Evo Plus 500 GB M.2-2280 NVME Solid State Drive]
|[Storage][Samsung 970 Evo Plus 1 TB M.2-2280 NVME Solid State Drive]
|[Video Card][Gigabyte GeForce RTX 3080 10 GB GAMING OC Video Card]

I am running `-wegnoegpu` in the `boot-arg` and relying on an iGPU which is enabled in the BIOS.

**Comment by Andr3y-** [comment]
Screenshot
![IMAGE 2021-04-11 22:03:27](https://user-images.githubusercontent.com/7428664/114321251-bea27800-9b11-11eb-9511-5e24b5dfd721.jpg)

**Comment by m33x** [comment]
Instead of communicating via GitHub issues, I think it would be better to ask such questions in the forum ([tonymacx86](https://www.tonymacx86.com/threads/ohchangs-build-gigabyte-z590-vision-g-i7-10700k-amd-rx580.310986/)).
Reading the manual I can answer your second question. tldr: You need to enable CSM Support in the BIOS.

<img width="666" alt="Screenshot 2021-04-18 at 21 32 54" src="https://user-images.githubusercontent.com/883685/115158308-c8862700-a08d-11eb-8454-545f642f89e6.png">
